# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
      - 'releases/**'
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
env:
  GITHUB_USERNAME : ${{ secrets.REPO_ACCESS_NAME}}
  GITHUB_TOKEN : ${{ secrets.REPO_ACCESS_TOKEN}} # scope all repos
  #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # scope this repo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set the env value
        id: step_one
        run: |
          echo "GITHUB_USERNAME=$GITHUB_USERNAME" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

      - name: echo the env value
        id: step_two
        run: |
          echo "GITHUB_USERNAME is ${{ env.GITHUB_USERNAME }}"
          echo "GITHUB_TOKEN is ${{ env.GITHUB_TOKEN }}"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.1

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.ACR_USER_NAME}}
          # Container registry password
          password: ${{ secrets.ACR_ACCESS_KEY}}
          # Container registry server url
          login-server: myjavaacr.azurecr.io

      - name: Build and push Docker images
        if: success() && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          context: .
          tags: myjavaacr.azurecr.io/address-service:${{ github.run_id }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Build and push Docker images
        if: success() && github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          context: .
          tags: myjavaacr.azurecr.io/address-service-dev:${{ github.run_id}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache



